name: CI

on: [push]

jobs:

  build:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Build Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'


    - name: Install dependencies
      run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

    